# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    close_sinks: ignore
    missing_required_param: error
    missing_return: error
    inference_failure_on_function_return_type: ignore
    avoid_dynamic_calls: ignore
    use_build_context_synchronously: ignore
    argument_type_not_assignable: ignore
    invalid_annotation_target: ignore
    public_member_api_docs: ignore
    only_throw_errors: ignore
    implicit_dynamic_method: ignore
    always_use_package_imports: ignore
    avoid_slow_async_io: ignore

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

  strong-mode:

linter:
  rules:
    public_member_api_docs: false
    unrelated_type_equality_checks: false
